name: Publish GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: 📤 Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            releases/${{ github.ref_name }}/*.exe
            releases/${{ github.ref_name }}/*.sig
            releases/${{ github.ref_name }}/latest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧹 Clean up repository except workflows
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name '.github' -exec rm -rf {} +
          find .github -mindepth 1 -maxdepth 1 ! -name 'workflows' -exec rm -rf {} +
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "🧹 Cleanup after release ${{ github.ref_name }}"
          git push origin HEAD:main
